name: Check for WordPress Updates

on:
  push:
    branches: [main]
  # schedule:
  # * is a special character in YAML so you have to quote this string
  # - cron: '*/15 * * * *'
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Lando Server
        run: |
          docker build - < Dockerfile;
          /usr/local/bin/terminus auth:login --machine-token=${{ secrets.TERMINUS_MACHINE_TOKEN }};
          /usr/local/bin/terminus  site:list --org "Dunder Mifflin"
      - name: Install WP
        run: |
          wp cli version
